//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.EmployeeContext.ExceptionResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HR.EmployeeContext.ExceptionResources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای کارمند فاقد قرارداد امکان تعریف شیفت وجود ندارد.
        /// </summary>
        public static string AssignShiftToEmployeeWithoutContractException {
            get {
                return ResourceManager.GetString("AssignShiftToEmployeeWithoutContractException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت ساعت ورود را صحیح وارد کنید. مثال 08:30.
        /// </summary>
        public static string AttendanceEntranceTimeInvalidFormatException {
            get {
                return ResourceManager.GetString("AttendanceEntranceTimeInvalidFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت خروج باید از ساعت ورود بزرگ تر باشد.
        /// </summary>
        public static string AttendanceExitTimeEarlierThanEntranceTimeException {
            get {
                return ResourceManager.GetString("AttendanceExitTimeEarlierThanEntranceTimeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت ساعت خروج را صحیح وارد کنید. مثال 19:30.
        /// </summary>
        public static string AttendanceExitTimeInvalidFormatException {
            get {
                return ResourceManager.GetString("AttendanceExitTimeInvalidFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازه ی ورود/خروج وارد شده با سایر ورود/خروج های روز مشخص شده تداخل دارد.
        /// </summary>
        public static string AttendanceTimeRangeConflictException {
            get {
                return ResourceManager.GetString("AttendanceTimeRangeConflictException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ قرارداد با تاریخ سایر قرارداد های موجود تداخل دارد.
        /// </summary>
        public static string ContractDateConflictException {
            get {
                return ResourceManager.GetString("ContractDateConflictException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد روزهای چرخه ی شیفت باید با تعداد شیفت های تعریف شده مساوی باشد.
        /// </summary>
        public static string CycleDurationInDaysNotQualToPatternsCountException {
            get {
                return ResourceManager.GetString("CycleDurationInDaysNotQualToPatternsCountException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی تکراری است.
        /// </summary>
        public static string DuplicateNationalCodeException {
            get {
                return ResourceManager.GetString("DuplicateNationalCodeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شیفت تکراری است.
        /// </summary>
        public static string DuplicateShiftNameException {
            get {
                return ResourceManager.GetString("DuplicateShiftNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارمند باید بزرگ تر از 18 سال یا کوچکتر از 40 سال باشد.
        /// </summary>
        public static string EmployeeAgeOutOfRangeException {
            get {
                return ResourceManager.GetString("EmployeeAgeOutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پایان نباید از تاریخ شروع قرارداد کوچکتر باشد.
        /// </summary>
        public static string EndDateEarlierThanStartDateException {
            get {
                return ResourceManager.GetString("EndDateEarlierThanStartDateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت تاریخ تولد صحیح نمی باشد.
        /// </summary>
        public static string InvalidBirthdateFormatException {
            get {
                return ResourceManager.GetString("InvalidBirthdateFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی نامعتبر است.
        /// </summary>
        public static string InvalidNationalCodeException {
            get {
                return ResourceManager.GetString("InvalidNationalCodeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول کد ملی باید 10 رقم باشد.
        /// </summary>
        public static string InvalidNationalCodeLengthException {
            get {
                return ResourceManager.GetString("InvalidNationalCodeLengthException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور باید شامل حداقل یک حرف بزرگ و کوچک انگلیسی باشد.
        /// </summary>
        public static string InvalidPasswordException {
            get {
                return ResourceManager.GetString("InvalidPasswordException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور نمی تواند کمتر از هشت کاراکتر یا بیشتر از پانزده کاراکتر باشد.
        /// </summary>
        public static string InvalidPasswordLengthException {
            get {
                return ResourceManager.GetString("InvalidPasswordLengthException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد روز تکرار شیفت نامعتبر است.
        /// </summary>
        public static string InvalidShiftPatternDayException {
            get {
                return ResourceManager.GetString("InvalidShiftPatternDayException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی باید عدد باشد.
        /// </summary>
        public static string NationalCodeNonNumberException {
            get {
                return ResourceManager.GetString("NationalCodeNonNumberException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت ورود را وارد کنید.
        /// </summary>
        public static string NullAttendanceEntranceTimeException {
            get {
                return ResourceManager.GetString("NullAttendanceEntranceTimeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت خروج را وارد کنید.
        /// </summary>
        public static string NullAttendanceExitTimeException {
            get {
                return ResourceManager.GetString("NullAttendanceExitTimeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا آدرس را وارد کنید.
        /// </summary>
        public static string NullOrEmptyAddressException {
            get {
                return ResourceManager.GetString("NullOrEmptyAddressException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام را وارد کنید.
        /// </summary>
        public static string NullOrEmptyFirstNameException {
            get {
                return ResourceManager.GetString("NullOrEmptyFirstNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی را وارد کنید.
        /// </summary>
        public static string NullOrEmptyLastNameException {
            get {
                return ResourceManager.GetString("NullOrEmptyLastNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی را وارد کنید.
        /// </summary>
        public static string NullOrEmptyNationalCodeException {
            get {
                return ResourceManager.GetString("NullOrEmptyNationalCodeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه ی عبور نمی تواند خالی باشد.
        /// </summary>
        public static string NullOrEmptyPasswordException {
            get {
                return ResourceManager.GetString("NullOrEmptyPasswordException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شیفت را وارد کنید.
        /// </summary>
        public static string NullOrEmptyShiftNameException {
            get {
                return ResourceManager.GetString("NullOrEmptyShiftNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ انتصاب شیفت را وارد کنید.
        /// </summary>
        public static string NullShiftAssignmentDateException {
            get {
                return ResourceManager.GetString("NullShiftAssignmentDateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت پایان شیفت را وارد کنید.
        /// </summary>
        public static string NullShiftPatternEndTimeException {
            get {
                return ResourceManager.GetString("NullShiftPatternEndTimeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت شروع شیفت را وارد کنید.
        /// </summary>
        public static string NullShiftPatternStartTimeException {
            get {
                return ResourceManager.GetString("NullShiftPatternStartTimeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قرارداد مورد نظر یافت نشد.
        /// </summary>
        public static string RequestedContractNotFoundException {
            get {
                return ResourceManager.GetString("RequestedContractNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتصاب شیفت برای کارمند باید در بازه ی زمانی قرارداد کارمند باشد.
        /// </summary>
        public static string ShiftAssignmentMustBeInContractDateRangeException {
            get {
                return ResourceManager.GetString("ShiftAssignmentMustBeInContractDateRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت ساعت پایان را صحیح وارد کنید. مثال: 19:00.
        /// </summary>
        public static string ShiftPatternEndTimeInvalidFormatException {
            get {
                return ResourceManager.GetString("ShiftPatternEndTimeInvalidFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت ساعت شروع را صحیح وارد کنید. مثال: 07:00.
        /// </summary>
        public static string ShiftPatternStartTimeInvalidFormatException {
            get {
                return ResourceManager.GetString("ShiftPatternStartTimeInvalidFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع باید از تاریخ پایان قرارداد قبلی بزرگ تر باشد.
        /// </summary>
        public static string StartDateEarlierThanLastEndDateException {
            get {
                return ResourceManager.GetString("StartDateEarlierThanLastEndDateException", resourceCulture);
            }
        }
    }
}
